travis:
  secure:
    BINSTAR_TOKEN: vJzmQFKbOOsTwX/7pvMKPKlUI628sVdXGlmC4ox/1KIAjPU/+ss4uU5mq7gGo4BiKIO5PNB1wxzBYbc6WQVHfr1XJvFJIJSCkkQWClSzq2H/lMBwJrzpkofzetm/flWIA0S8UsyaIx5KIralv1dUSsfUPePndnRVk96H9fSEI8KhJ0xIQ9bxDP2cHM8gxCzjgMYnBLI+U2ba4FLWN6gAgCSqwPKOFpMVqZOcoqNOQW9eVGG0cP/h8oKtfMogiSbnm0SFrvXmBlShEekdYqgG8KEN6ktkryXVlRKKLSpUcWrLyJLv1Q0CAcHloz1bAPXP2NFFKCbcKvkO6CktNCytxT73n/3Nt2JB/wz5ZVAGxNHhhpwuLVSiFvjF+nf26LXDY/vo5g3IpqRj43fLvDdtw1HFpodLj809jRP0osciKSLpJgzfPH1l7qESCbL9badAI/wWVVg3iO+Z3Hra5Ij4UREmiQDJSzavGoszrABd75PtVLtuX3MmDQIn9AdeOw5bwEnfMUkX8TS0oG3SrvMkEiNxlsp3ponI6V7aKZQT2/twc7GLdTk9s9es2X1DcjIs7nIgVkG0wWC5PNj3faL8kHTuEwyHiA/O/a1xyA3595oDXqZpnOOG1x1fcCf4+nlHoNVdtbFC5WHOiEmQp8zdYZGjiEoZb2+0GIpTT1SXN5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
